CREATE TABLE GUESTBOOK (
    IDX NUMBER PRIMARY KEY, 
    NAME VARCHAR2(30),
    SUBJECT VARCHAR2(100),
    CONTENT VARCHAR2(1000),
    EMAIL VARCHAR2(100),
    PWD VARCHAR2(30),
    REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE GUESTBOOK_SEQ NOCACHE;

INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '全老悼', '力格', '郴侩', 'HONG@TEST.COM',
    '1111', SYSDATE - 3);
INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '全捞悼', '力格12', '郴侩2', 'HONG2@TEST.COM',
    '2222', SYSDATE - 2);
INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '全伙悼', '力格3', '郴侩3', 'HONG3@TEST.COM',
    '3333', SYSDATE - 1);