CREATE TABLE MEMBER2(
    IDX NUMBER(5) PRIMARY KEY,
    ID VARCHAR2(10),
    PWD VARCHAR2(10),
    NAME VARCHAR2(30),
    AGE NUMBER(3),
    ADDRESS VARCHAR2(150),
    REG DATE
);
CREATE SEQUENCE MEMBER_SEQ;
INSERT INTO MEMBER
    (IDX, ID, PWD, NAME, AGE, ADDRESS, REG)
VALUES (MEMBER_SEQ.NEXTVAL, 'admin', 'admin', '������', null, null, SYSDATE);
INSERT INTO MEMBER
    (IDX, ID, PWD, NAME, AGE, ADDRESS, REG)
VALUES (MEMBER_SEQ.NEXTVAL, 'test1', 'test1', 'ȫ�浿', 27, '����', SYSDATE);

 		INSERT INTO MEMBER2
		       (IDX, ID, PWD, NAME, AGE, ADDRESS, REG)
		VALUES (MEMBER_SEQ.NEXTVAL, #{id}, #{pwd}, #{name}, #{age}, 
		        #{address}, SYSDATE)

SELECT * FROM MEMBER;
